JquerySolution/Models/Image.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JquerySolution.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int ImageId { get; set; }
        public string Image1 { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}

JquerySolution/Controllers/ManageEmployeeController.cs
using System;
using System.IO;
using System.Web.Mvc;
using JquerySolution.Models;
using static System.IO.Directory;

namespace JquerySolution.Controllers
{
    public class ManageEmployeeController : Controller
    {
        public ModelServices Ms = new ModelServices();

        [HttpGet]
        public ActionResult EmployeeList()
        {
            ViewBag.EmployeeList = Ms.GetEmployee();
            ViewBag.CountryList = Ms.GetCountry();
            return View();
        }

        public JsonResult GetEmployeeList()
        {
            ViewBag.EmployeeList = Ms.GetEmployee();
            return Json("true", JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult AddEmployeerPartialView()
        {
            return PartialView("_AddEmployee");
        }

        public PartialViewResult EditEmployeerPartialView()
        {
            return PartialView("_EditEmployee");
        }

        public JsonResult InsertEmployee(string city, string name, string department, string mobile)
        {
            Employee employee = new Employee()
            {
                Name = name,
                Department = department,
                CityId = int.Parse(city),
                Mobile = long.Parse(mobile)
            };
            Ms.AddEmployee(employee);
            ViewBag.EmployeeList = Ms.GetEmployee();
            var countrylist = Ms.GetCountry();
            return Json(new SelectList(countrylist.ToArray(), "CountryId", "Country1", countrylist), JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateEmployee(string city, string name, string department, string mobile,string employee)
        {
            Employee emp = new Employee();
            emp.EmpId = int.Parse(employee);
            emp.Name = name;
            emp.Department = department;
            emp.Mobile = long.Parse(mobile);
            emp.CityId = int.Parse(city);
            Ms.UpdateEmployee(emp);
            ViewBag.EmployeeList = Ms.GetEmployee();
            return Json(new {success=true}, JsonRequestBehavior.AllowGet);
        }

        public JsonResult EditEmployee(string id)
        {
            Employee emp = Ms.GetEmployeeDetail(int.Parse(id));
            return Json(new
            {
                empid = emp.EmpId.ToString(),
                EName = emp.Name,
                DName = emp.Department,
                Mobile = emp.Mobile.ToString(),
                CityId = emp.CityId.ToString(),
                CName = emp.City.City1,
                StateId = emp.City.StateId.ToString(),
                SName = emp.City.State.State1,
                CoName=emp.City.State.Country.Country1,
                CountryId=emp.City.State.CountryId.ToString()
            }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult DeleteEmployee(string id)
        {
            Employee emp = Ms.GetEmployeeDetail(int.Parse(id));
            Ms.DeleteEmployee(emp);
            ViewBag.EmployeeList = Ms.GetEmployee();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult MultiDeleteEmployee(string id)
        {
            var eid = id.Split(',');
            foreach (var data in eid)
            {
                Employee emp = Ms.GetEmployeeDetail(int.Parse(data));
                Ms.DeleteEmployee(emp);
            }
            ViewBag.EmployeeList = Ms.GetEmployee();
            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }
        
        public JsonResult InsertCountry(string countryname)
        {
            Country country = new Country()
            {
                Country1 = countryname
            };
            int id = Ms.AddCountry(country);
            ViewBag.CountryList = Ms.GetCountry();
            var countrylist = Ms.GetCountry();
            return Json(new SelectList(countrylist.ToArray(), "CountryId", "Country1", countrylist), JsonRequestBehavior.AllowGet);
        }

        public JsonResult BindCountry()
        {
            var country = Ms.GetCountry();
            return Json(new SelectList(country.ToArray(), "CountryId", "Country1"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult BindCityList(int id)
        {
            var city = Ms.GetCityByStateId(id);
            return Json(new SelectList(city.ToArray(), "CityId", "City1"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult BindStateList(int id)
        {
            var state = Ms.GetStateByCountryId(id);
            return Json(new SelectList(state.ToArray(), "StateId", "State1"), JsonRequestBehavior.AllowGet);
        }

        public JsonResult UploadFiles(int id)
        {
            if (Request.Files.Count > 0)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];
                    if (file != null)
                    {
                        var imagename = file.FileName;
                        var changename = Guid.NewGuid() + imagename;
                        var imageext = Path.GetExtension(imagename);
                        CreateDirectory(Server.MapPath("~/Images/" + id));
                        file.SaveAs(Server.MapPath("~/Images/" + id + "/") + changename);
                        Image image=new Image()
                        {
                            EmployeeId = id,
                            Image1 = changename
                        };
                        Ms.AddImage(image);
                    }
                }
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            return Json(new { success = false }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult ImageListByEmpId(int id)
        {
            var imagelist = Ms.GetImagesByEid(id);
            return Json(new SelectList(imagelist.ToArray(), "EmployeeId", "Image1"), JsonRequestBehavior.AllowGet);
        }
    }
}

JquerySolution/Views/ManageEmployee/EmployeeList.cshtml
@{
    ViewBag.Title = "EmployeeList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<link href="~/Content/lightbox.css" rel="stylesheet" />
<script src="~/Scripts/lightbox.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#EmployeeList").on('click', '.deleteemp', function () {
            //debugger;
            var id = $(this).data('id');
            //alert(id);
            $.ajax({
                type: "POST",
                url: "/ManageEmployee/DeleteEmployee",
                data: "{'id':'" + id + "'}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (result) {
                    $("#EmployeeList").load(" #EmployeeList");
                }
            });
        });

        $("#EmployeeList").on('click', '.editemp', function () {
            var id = $(this).data('eid');
            var stateid = null, cityid = null;
            $.ajax({
                type: "POST",
                url: "/ManageEmployee/EditEmployee",
                data: "{'id':'" + id + "'}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (result) {
                    debugger;
                    $("#txtEID").val(result.empid);
                    $("#txtEditName").val(result.EName);
                    $("#txtEditDepartment").val(result.DName);
                    $("#txtEditMobile").val(result.Mobile);
                    stateid = result.StateId;
                    cityid = result.CityId;
                    $("#txtEditCountry").val(result.CountryId);

                    $('#txtEditState').empty();
                    $.getJSON('/ManageEmployee/BindStateList/' + result.CountryId, function (data) {
                        var items = '<option value="">Select a State</option>';
                        $.each(data, function (i, state) {
                            items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                        });
                        $('#txtEditState').html(items);
                        $("#txtEditState").val(stateid);
                    });

                    $('#txtEditCity').empty();
                    $.getJSON('/ManageEmployee/BindCityList/' + result.StateId, function (data) {
                        var items = '<option value="">Select a City</option>';
                        $.each(data, function (i, state) {
                            items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                        });
                        $('#txtEditCity').html(items);
                        $("#txtEditCity").val(cityid);
                    });
                }
            });
        });

        $("#EmployeeList").on('click', '.addimage', function () {
            //debugger;
            var id = $(this).data('eiid');
            $("#txtImgEmpId").val(id);
        });

        $("#EmployeeList").on('click', '.multideleteemp', function () {
            //debugger;
            var empid = [];
            $(".del_chk:checked").each(function () {
                empid.push($(this).attr('data-eid'));
            });
            if (empid.length > 0) {
                $.ajax({
                    type: "POST",
                    url: "/ManageEmployee/MultiDeleteEmployee",
                    data: "{'id':'" + empid + "'}",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {
                        $("#EmployeeList").load(" #EmployeeList");
                    }
                });
            }
        });

        $("#EmployeeList").on('change', '.del_chk', function () {
            var length = $('.del_chk').length;
            if ($('.del_chk:checked').length === $('.del_chk').length) {
                $("#alldeletechk")[0].checked = true;
            } else {
                $("#alldeletechk")[0].checked = false;
            }
        });

        $("#EmployeeList").on('change', '#alldeletechk', function () {
            if ($(this).prop('checked')) {
                $('.del_chk').prop('checked', true);
            }
            else {
                $('.del_chk').prop('checked', false);
            }
        });

        //$('.del_chk').change(function () {
        //    var length = $('.del_chk').length;
        //    if ($('.del_chk:checked').length === $('.del_chk').length) {
        //        $("#alldeletechk")[0].checked = true;
        //    } else {
        //        $("#alldeletechk")[0].checked = false;
        //    }
        //});

        //$("#alldeletechk").change(function () {
        //    if ($(this).prop('checked')) {
        //        $('.del_chk').prop('checked', true);
        //    }
        //    else {
        //        $('.del_chk').prop('checked', false);
        //    }
        //});
    });
</script>


<!-- Button trigger modal -->

<div id="EmployeeTable" class="table-responsive">
    <h2>EmployeeList</h2>
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal" style="margin-left:988px; margin-bottom: 5px;">
        Add Employee
    </button>

    <table id="EmployeeList" class="table table-bordered ">
        <thead>
            <tr>
                <td style="width: 120px;" align="center">
                    <input type="button" value="Delete" id="btnMultiDeleteEmployee" class="btn btn-info multideleteemp" />
                </td>
                <td align="center">
                    <b>Index</b>
                </td>
                <td align="center">
                    <b>Name</b>
                </td>
                <td align="center">
                    <b>Department</b>
                </td>
                <td align="center">
                    <b>Mobile</b>
                </td>
                <td align="center">
                    <b>City</b>
                </td>
                <td align="center">
                    <b>State</b>
                </td>
                <td align="center">
                    <b>Country</b>
                </td>
                <td align="center"></td>
            </tr>
        </thead>
        <tbody>
            @if (ViewBag.EmployeeList != null)
            {
                int i = 0;
                foreach (var item in ViewBag.EmployeeList)
                {
                    i = i + 1;
                    <tr align="center">
                        <td>
                            <input type="checkbox" class="del_chk" data-eid="@item.EmpId">
                        </td>
                        <td>
                            @i
                        </td>
                        <td class="employeename">
                            @item.Name
                        </td>
                        <td class="departmentname">
                            @item.Department
                        </td>
                        <td>
                            @item.Mobile
                        </td>
                        <td>
                            @item.City.City1
                        </td>
                        <td>
                            @item.City.State.State1
                        </td>
                        <td>
                            @item.City.State.Country.Country1
                        </td>
                        <td style="width: 250px;">
                            <button type="button" id="btnEditEmployee" class="btn btn-info editemp" data-eid="@item.EmpId" data-toggle="modal" data-target="#EditModal">
                                Edit
                            </button>
                            <input type="button" value="Delete" id="btnDeleteEmployee" data-id="@item.EmpId" class="btn btn-info deleteemp" />
                            <button type="button" id="btnAddEmpoyeeImage" class="btn btn-info addimage" data-eiid="@item.EmpId" data-toggle="modal" data-target="#AddImageModal">
                                Images
                            </button>
                        </td>
                    </tr>
                }
            }
        </tbody>
        <tfoot>
            <tr align="center">
                <td style="width: 120px;">
                    <input type="checkbox" id="alldeletechk" />
                </td>
                <td align="center">
                    <b>Index</b>
                </td>
                <td align="center">
                    <b>Name</b>
                </td>
                <td align="center">
                    <b>Department</b>
                </td>
                <td align="center">
                    <b>Mobile</b>
                </td>
                <td align="center">
                    <b>City</b>
                </td>
                <td align="center">
                    <b>State</b>
                </td>
                <td align="center">
                    <b>Country</b>
                </td>
                <td align="center"></td>
            </tr>
        </tfoot>
    </table>
</div>

<br />

<!--Add Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Add Employee</h4>
            </div>
            <div class="modal-body">
                @Html.Partial("_AddEmployee")
            </div>
            @*<div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>*@
        </div>
    </div>
</div>

<!--Edit Modal -->
<div class="modal fade" id="EditModal" tabindex="-1" role="dialog" aria-labelledby="EditmyModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="EditmyModalLabel">Edit Employee</h4>
            </div>
            <div class="modal-body">
                @Html.Partial("_EditEmployee")
            </div>
            @*<div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>*@
        </div>
    </div>
</div>

<!--Add Image-->
<div class="modal fade" id="AddImageModal" tabindex="-1" role="dialog" aria-labelledby="ImagemyModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="ImagemyModalLabel">Images</h4>
            </div>
            <div class="modal-body">
                @Html.Partial("_ImageForm")
            </div>
            @*<div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>*@
        </div>
    </div>
</div>

<!--Image List-->
<div class="modal fade" id="ImageListByIdModal" tabindex="-1" role="dialog" aria-labelledby="ImageListmyModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="ImageListmyModalLabel">Images</h4>
            </div>
            <div class="modal-body">
                @Html.Partial("_ImageList")
            </div>
        </div>
    </div>
</div>
@*<img src="~/Images/2/30823076-b291-408b-9a17-be18de30f619IMG_1254.JPG" style="height: 20px; width: 150px;" />*@

@*<img src="~/Images/2/30823076-b291-408b-9a17-be18de30f619IMG_1254.JPG" style="height: 150px; width: 150px;" />*@
@*<a href="~/Images/2/30823076-b291-408b-9a17-be18de30f619IMG_1254.JPG" data-lightbox="30823076-b291-408b-9a17-be18de30f619IMG_1254" data-title="My caption">Image #1</a>*@

JquerySolution/Views/ManageEmployee/_AddEmployee.cshtml
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        var path = "@Url.Action("BindStateList", "ManageEmployee")";
        $("#txtCountry").change(function () {
            //debugger;
            //var selectitem = $('#txtCountry option:selected').text();
            if (($('#txtCountry option:selected').text() === "Select Country")) {
                $('#txtState').empty();
                var item1 = '<option value="">Select State</option>';
                $('#txtState').html(item1);
            }
            else {
                $('#txtState').empty();
                var items = '<option value="">Select State</option>';
                $.getJSON('/ManageEmployee/BindStateList/' + $('#txtCountry').val(), function (data) {
                    $.each(data, function (i, state) {
                        items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                    });
                    $('#txtState').html(items);
                });
            }
        });

        $("#txtState").change(function () {
            if (($('#txtState option:selected').text() === "Select State")) {
                $('#txtCity').empty();
                var item1 = '<option value="">Select City</option>';
                $('#txtCity').html(item1);
            }
            else {
                $('#txtCity').empty();
                var items = '<option value="">Select City</option>';
                $.getJSON('/ManageEmployee/BindCityList/' + $('#txtState').val(), function (data) {
                    $.each(data, function (i, state) {
                        items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                    });
                    $('#txtCity').html(items);
                });
            }

        });

        $("#btnInsert").click(function () {

            var obj = {};
            obj.city = $("#txtCity").val();
            obj.name = $("#txtName").val();
            obj.mobile = $("#txtMobile").val();
            obj.department = $("#txtDepartment").val();
            $.ajax({
                type: "POST",
                url: "/ManageEmployee/InsertEmployee",
                data: "{'city':'" + obj.city + "','name':'" + obj.name + "','department':'" + obj.department + "','mobile':'" + obj.mobile + "'}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (data) {
                    //debugger;
                    $('#txtName').val('');
                    $("#txtDepartment").val('');
                    $("#txtMobile").val('');
                    $("#txtCountry").empty();
                    $("#txtState").empty();
                    $("#txtCity").empty();
                    var items = '<option value="">Select Country</option>';
                    var item1 = '<option value="">Select State</option>';
                    var item2 = '<option value="">Select City</option>';
                    $.each(data, function (i, countrylist) {
                        items += "<option value='" + countrylist.Value + "'>" + countrylist.Text + "</option>";
                    });
                    $('#txtCountry').html(items);
                    $('#txtState').append(item1);
                    $('#txtCity').append(item2);
                    $("#EmployeeList").load(" #EmployeeList");
                    $('#myModal').modal('hide');
                }
            });
        });

    });
</script>

<form>
    <div class="form-group">
        <label>Name</label>
        <input type="text" name="txtName" id="txtName" class="form-control" />
    </div>
    <div class="form-group">
        <label>Department</label>
        <input type="text" name="txtDepartment" id="txtDepartment" class="form-control" />
    </div>
    <div class="form-group">
        <label>Mobile</label>
        <input type="text" name="txtMobile" id="txtMobile" class="form-control" />
    </div>

    <div class="form-group">
        <div>
            <label>Country</label>
        </div>
        <div>
            <select name="txtCountry" id="txtCountry" class="form-control" style="display:inline-block;">
                <option value="">Select Country</option>
                @foreach (var data in ViewBag.CountryList)
                {
                    <option value="@data.CountryId">@data.Country1</option>
                }
            </select>
            <button type="button" id="btnCountryClick" data-toggle="modal" class="btn btn-info" data-target="#myModalCountry">
                Add Country
            </button>
           @*@Html.DropDownList("PriorityID", (IEnumerable<SelectListItem>)ViewBag.PriorityID,"Select Country", new { @class = "dropdown" })*@
        </div>
     
    </div>
    <div class="form-group">
        <label>State</label>
        <select name="txtState" id="txtState" class="form-control">
            <option value="">Select State</option>
        </select>
    </div>
    <div class="form-group">
        <label>City</label>
        <select name="txtCity" id="txtCity" class="form-control">
            <option value="">Select City</option>
        </select>
    </div>
    @*<input type="button" name="btnInsert" value="Insert" id="btnInsert" data-dismiss="modal" class="btn btn-default" />*@
    <input type="button" name="btnInsert" value="Insert" id="btnInsert" class="btn btn-default" />
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</form>

<!-- Modal -->
<div class="modal fade" id="myModalCountry" tabindex="-1" role="dialog"  aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Insert Country</h4>
                
            </div>
            <div class="modal-body">
                @Html.Partial("_AddCountry")
            </div>
        </div>
    </div>
</div>

JquerySolution/Views/ManageEmployee/_EditEmployee.cshtml
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
        $(document).ready(function () {
            var path = "@Url.Action("BindStateList", "ManageEmployee")";
            $("#txtEditCountry").change(function () {
                $('#txtEditState').empty();
                $.getJSON('/ManageEmployee/BindStateList/' + $('#txtEditCountry').val(), function (data) {
                    var items = '<option value="">Select a State</option>';
                    $.each(data, function (i, state) {
                        items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                    });
                    $('#txtEditState').html(items);
                });
            });

            $("#txtEditState").change(function () {
                $('#txtEditCity').empty();
                $.getJSON('/ManageEmployee/BindCityList/' + $('#txtEditState').val(), function (data) {
                    var items = '<option value="">Select a City</option>';
                    $.each(data, function (i, state) {
                        items += "<option value='" + state.Value + "'>" + state.Text + "</option>";
                    });
                    $('#txtEditCity').html(items);
                });
            });

            $("#btnUpdate").click(function () {
                //debugger;
                var obj = {};
                obj.city = $("#txtEditCity").val();
                obj.name = $("#txtEditName").val();
                obj.mobile = $("#txtEditMobile").val();
                obj.department = $("#txtEditDepartment").val();
                obj.Eid = $("#txtEID").val();
                $.ajax({
                    type: "POST",
                    url: "/ManageEmployee/UpdateEmployee",
                    data: "{'city':'" + obj.city + "','name':'" + obj.name + "','department':'" + obj.department + "','mobile':'" + obj.mobile + "','employee':'" + obj.Eid + "'}",
                    contentType: "application/json; charset=utf-8",
                    dataType: "json",
                    success: function (result) {
                        $("#EmployeeList").load(" #EmployeeList");
                        $('#EditModal').modal('hide');
                    }
                });

            });
        });
</script>

<form>
    <div class="form-group">
        <label>Name</label>
        <input type="text" name="txtEditName" id="txtEditName" class="form-control" />
        <input type="hidden" name="txtEID" id="txtEID" />
    </div>
    <div class="form-group">
        <label>Department</label>
        <input type="text" name="txtEditDepartment" id="txtEditDepartment" class="form-control" />
    </div>
    <div class="form-group">
        <label>Mobile</label>
        <input type="text" name="txtEditMobile" id="txtEditMobile" class="form-control" />
    </div>
    <div class="form-group">
        <label>Country</label>
        <select name="txtEditCountry" id="txtEditCountry" class="form-control">
            <option value="">Select Country</option>
            @foreach (var data in ViewBag.CountryList)
            {
                <option value="@data.CountryId">@data.Country1</option>
            }
        </select>

    </div>
    <div class="form-group">
        <label>State</label>
        <select name="txtEditState" id="txtEditState" class="form-control">
            <option value="">Select State</option>
        </select>
    </div>
    <div class="form-group">
        <label>City</label>
        <select name="txtEditCity" id="txtEditCity" class="form-control">
            <option value="">Select City</option>
        </select>
    </div>
    <input type="button" name="btnUpdate" value="Update" id="btnUpdate" class="btn btn-default" />
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
</form>

JquerySolution/Views/ManageEmployee/_ImageList.cshtml
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#btnImageListClose").click(function () {
            $('#AddImageModal').modal('show');
            $('#ImageListByIdModal').modal('hide');
        });
    });
</script>



<form>
    <div class="form-group">
        <label>Images</label>
        <input type="hidden" name="txtImgListEmpId" id="txtImgListEmpId" />
    </div>
    
    <div id="imagelistforemployee">
        
    </div>
    
    <div style="margin-top: 15px">
        <input type="button" name="btnImageInsert" value="Add Image" id="btnImageListClose" class="btn btn-default" />
        <input type="button" name="btnImageInsert" value="Close" data-dismiss="modal"  class="btn btn-default" />
    </div>
</form>